"""
ResNet-50 Backbone with LoRA injection support.

All pretrained weights are frozen (requires_grad=False).
Layer3 (Stage 4) and Layer4 (Stage 5) convolution layers support
LoRA injection via the equation:

    W_adaptive = W_pretrained + U @ V^T

where (U, V) are generated by the LoRAGenerator from z_lora.

Feature outputs: S3 (stride 8), S4 (stride 16), S5 (stride 32)

Pretrained weights are loaded from torchvision's ResNet-50
(ImageNet-1K) and mapped to the frozen conv/bn layers.
"""

from __future__ import annotations

import re
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Frozen building blocks (pretrained weights, no gradient)
# ---------------------------------------------------------------------------


class FrozenConv2d(nn.Module):
    """Conv2d with frozen pretrained weight and bias."""

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int = 1,
        padding: int = 0,
        bias: bool = False,
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = (kernel_size, kernel_size) if isinstance(kernel_size, int) else kernel_size
        self.stride = (stride, stride) if isinstance(stride, int) else stride
        self.padding = (padding, padding) if isinstance(padding, int) else padding

        w = torch.empty(out_channels, in_channels, *self.kernel_size)
        nn.init.kaiming_uniform_(w, mode="fan_out", nonlinearity="relu")
        self.weight = nn.Parameter(w, requires_grad=False)
        self.bias = nn.Parameter(torch.zeros(out_channels), requires_grad=False) if bias else None

    def forward(
        self, x: torch.Tensor,
        U: Optional[torch.Tensor] = None, V: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        return F.conv2d(x, self.weight, self.bias, self.stride, self.padding)


class LoRAConv2d(nn.Module):
    """
    Conv2d with frozen weight + LoRA delta injection.

    During forward, computes:
        W_eff = W_frozen + delta
    where delta = U @ V^T reshaped to conv weight shape.
    If no (U,V) provided, behaves as FrozenConv2d.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int = 1,
        padding: int = 0,
        bias: bool = False,
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = (kernel_size, kernel_size) if isinstance(kernel_size, int) else kernel_size
        self.stride = (stride, stride) if isinstance(stride, int) else stride
        self.padding = (padding, padding) if isinstance(padding, int) else padding

        w = torch.empty(out_channels, in_channels, *self.kernel_size)
        nn.init.kaiming_uniform_(w, mode="fan_out", nonlinearity="relu")
        self.weight_frozen = nn.Parameter(w, requires_grad=False)
        self.bias = nn.Parameter(torch.zeros(out_channels), requires_grad=False) if bias else None

        self._weight_shape = w.shape

    def forward(
        self, x: torch.Tensor, U: Optional[torch.Tensor] = None, V: Optional[torch.Tensor] = None
    ) -> torch.Tensor:
        weight = self.weight_frozen
        if U is not None and V is not None:
            delta = U @ V.T
            weight = weight + delta.view_as(weight)
        return F.conv2d(x, weight, self.bias, self.stride, self.padding)


class FrozenBatchNorm2d(nn.Module):
    """BatchNorm2d with all parameters and running stats frozen."""

    def __init__(self, num_features: int):
        super().__init__()
        self.num_features = num_features
        self.weight = nn.Parameter(torch.ones(num_features), requires_grad=False)
        self.bias = nn.Parameter(torch.zeros(num_features), requires_grad=False)
        self.register_buffer("running_mean", torch.zeros(num_features))
        self.register_buffer("running_var", torch.ones(num_features))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return F.batch_norm(
            x, self.running_mean, self.running_var, self.weight, self.bias, training=False, eps=1e-5
        )


# ---------------------------------------------------------------------------
# Bottleneck (ResNet-50)
# ---------------------------------------------------------------------------


class Bottleneck(nn.Module):
    expansion = 4

    def __init__(
        self,
        in_planes: int,
        planes: int,
        stride: int = 1,
        downsample: Optional[nn.Module] = None,
        use_lora: bool = False,
    ):
        """
        Args:
            in_planes:  input channels
            planes:     bottleneck channels (out = planes * expansion)
            stride:     stride for conv2 (spatial downsampling)
            downsample: shortcut projection when dimensions change
            use_lora:   whether conv layers accept LoRA injection
        """
        super().__init__()
        Conv = LoRAConv2d if use_lora else FrozenConv2d

        self.conv1 = Conv(in_planes, planes, kernel_size=1)
        self.bn1 = FrozenBatchNorm2d(planes)

        self.conv2 = Conv(planes, planes, kernel_size=3, stride=stride, padding=1)
        self.bn2 = FrozenBatchNorm2d(planes)

        self.conv3 = Conv(planes, planes * self.expansion, kernel_size=1)
        self.bn3 = FrozenBatchNorm2d(planes * self.expansion)

        self.downsample = downsample
        self.stride = stride

    def forward(
        self,
        x: torch.Tensor,
        lora: Optional[Dict[str, Tuple[torch.Tensor, torch.Tensor]]] = None,
        prefix: str = "",
    ) -> torch.Tensor:
        identity = x

        def _get_lora(suffix: str) -> Tuple[Optional[torch.Tensor], Optional[torch.Tensor]]:
            if lora is None:
                return None, None
            key = f"{prefix}{suffix}" if prefix else suffix
            return lora.get(key, (None, None))

        u1, v1 = _get_lora("conv1")
        out = F.relu(self.bn1(self.conv1(x, u1, v1)))

        u2, v2 = _get_lora("conv2")
        out = F.relu(self.bn2(self.conv2(out, u2, v2)))

        u3, v3 = _get_lora("conv3")
        out = self.bn3(self.conv3(out, u3, v3))

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        return F.relu(out)


# ---------------------------------------------------------------------------
# ResNet-50 Backbone
# ---------------------------------------------------------------------------


class ResNet50Backbone(nn.Module):
    """
    ResNet-50 backbone with LoRA injection on layer3 (Stage 4) and
    layer4 (Stage 5). Outputs multi-scale features S3, S4, S5.

    Architecture:
        conv1 (7x7, stride 2) + maxpool (3x3, stride 2)
        layer1: 3  Bottleneck [256]  stride 4  -> S3
        layer2: 4  Bottleneck [512]  stride 8  -> (not used as output in RT-DETR)
        layer3: 6  Bottleneck [1024] stride 16 -> S4  [LoRA]
        layer4: 3  Bottleneck [2048] stride 32 -> S5  [LoRA]
    """

    def __init__(
        self,
        lora_layer3: bool = True,
        lora_layer4: bool = True,
        pretrained: bool = True,
    ):
        super().__init__()
        self.in_planes = 64

        self.conv1 = FrozenConv2d(3, 64, kernel_size=7, stride=2, padding=3)
        self.bn1 = FrozenBatchNorm2d(64)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(64, 3, stride=1, use_lora=False)
        self.layer2 = self._make_layer(128, 4, stride=2, use_lora=False)
        self.layer3 = self._make_layer(256, 6, stride=2, use_lora=lora_layer3)
        self.layer4 = self._make_layer(512, 3, stride=2, use_lora=lora_layer4)

        self._out_channels = {"S3": 512, "S4": 1024, "S5": 2048}

        if pretrained:
            self._load_pretrained()

    def _make_layer(
        self, planes: int, blocks: int, stride: int, use_lora: bool
    ) -> nn.ModuleList:
        layers = []
        downsample = None
        if stride != 1 or self.in_planes != planes * Bottleneck.expansion:
            downsample = nn.Sequential(
                FrozenConv2d(self.in_planes, planes * Bottleneck.expansion, kernel_size=1, stride=stride),
                FrozenBatchNorm2d(planes * Bottleneck.expansion),
            )

        layers.append(Bottleneck(self.in_planes, planes, stride, downsample, use_lora=use_lora))
        self.in_planes = planes * Bottleneck.expansion
        for _ in range(1, blocks):
            layers.append(Bottleneck(self.in_planes, planes, use_lora=use_lora))

        return nn.ModuleList(layers)

    def forward(
        self, x: torch.Tensor, lora: Optional[Dict[str, Tuple[torch.Tensor, torch.Tensor]]] = None
    ) -> Dict[str, torch.Tensor]:
        """
        Args:
            x:     (B, 3, H, W)
            lora:  dict mapping layer name -> (U, V) from LoRAGenerator

        Returns:
            dict with keys 'S3', 'S4', 'S5' -> feature maps
        """
        if lora is None:
            lora = {}

        x = self.conv1(x)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.maxpool(x)

        x = self._forward_layer(self.layer1, x, lora, "backbone.layer1.")
        x = self._forward_layer(self.layer2, x, lora, "backbone.layer2.")
        s3 = x

        x = self._forward_layer(self.layer3, x, lora, "backbone.layer3.")
        s4 = x

        x = self._forward_layer(self.layer4, x, lora, "backbone.layer4.")
        s5 = x

        return {"S3": s3, "S4": s4, "S5": s5}

    def _forward_layer(self, layer_list, x, lora, prefix):
        for i, block in enumerate(layer_list):
            x = block(x, lora, f"{prefix}{i}.")
        return x

    @property
    def out_channels(self) -> Dict[str, int]:
        return self._out_channels

    def _load_pretrained(self):
        """Load ImageNet-1K pretrained weights from torchvision ResNet-50."""
        try:
            from torchvision.models import resnet50, ResNet50_Weights
            tv = resnet50(weights=ResNet50_Weights.IMAGENET1K_V1)
        except Exception:
            try:
                from torchvision.models import resnet50
                tv = resnet50(pretrained=True)
            except Exception:
                print("[WARN] Could not load ImageNet pretrained weights. Using random init.")
                return

        tv_state = tv.state_dict()

        for key in list(tv_state.keys()):
            if re.match(r'layer[34]\.\d+\.conv[123]\.weight$', key):
                new_key = key.replace('.weight', '.weight_frozen')
                tv_state[new_key] = tv_state.pop(key)

        missing, unexpected = self.load_state_dict(tv_state, strict=False)
        if missing:
            print(f"[BACKBONE] Missing keys (expected for LoRA/frozen): {len(missing)}")
        print(f"[BACKBONE] ImageNet-1K pretrained weights loaded.")


def build_backbone(
    lora_layer3: bool = True,
    lora_layer4: bool = True,
    pretrained: bool = True,
) -> ResNet50Backbone:
    return ResNet50Backbone(
        lora_layer3=lora_layer3,
        lora_layer4=lora_layer4,
        pretrained=pretrained,
    )
